AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - log/**/*
    - public/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - tmp/**/*
    - vendor/**/*
    - node_modules/**/*
    - Guardfile
    - .gems/**/*
    - tyr/**/*

Metrics/BlockLength:
  Max: 250

Metrics/ClassLength:
  Max: 150

Rails:
  Enabled: true

Metrics/ModuleLength:
  CountComments: false  # count full line comments?
  Max: 100
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/WordArray:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 20

Metrics/AbcSize:
  Max: 30

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/Delegate:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/RegexpLiteral:
  AllowInnerSlashes: true

Naming/PredicateName:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Lint/AssignmentInCondition:
  Enabled: false

Lint/NestedMethodDefinition:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 30

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: false

Security/YAMLLoad:
  Exclude:
    - 'spec/**/**'
    - 'app/storages/base_storage.rb'

Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/RescueStandardError:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Metrics/ParameterLists:
  Max: 8

Security/Eval:
  Exclude:
    - 'spec/steps/api/data_format_matcher_steps.rb'
    - 'spec/steps/response_steps.rb'
    - 'spec/steps/model_steps.rb'

Lint/UnusedBlockArgument:
  Exclude:
    - 'spec/steps/response_steps.rb'
    - 'spec/steps/model_steps.rb'

Lint/UselessAssignment:
  Exclude:
    - 'spec/steps/response_steps.rb'
    - 'spec/steps/model_steps.rb'

Lint/Debugger:
  Exclude:
    - 'spec/steps/util_steps.rb'

Rails/UnknownEnv:
  Environments: development, test, production, staging

Style/MixinUsage:
  Exclude:
    - 'spec/turnip_helper.rb'
    - 'spec/rails_helper.rb'
